# Generated by Django 3.1.3 on 2021-01-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210108_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
