# Generated by Django 3.1.3 on 2021-02-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='URL',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
