# Generated by Django 3.1.3 on 2021-02-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateURLS', models.TextField()),
            ],
        ),
    ]
