# Generated by Django 3.1.3 on 2021-02-03 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_posttemplates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='URL',
        ),
        migrations.AddField(
            model_name='post',
            name='Template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.posttemplates'),
        ),
    ]
