# Generated by Django 3.1.3 on 2020-12-31 13:39

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Hello', verbose_name=django.contrib.auth.models.User),
        ),
    ]
