# Generated by Django 3.1.3 on 2021-01-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_diaryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryitem',
            name='name',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
