# Generated by Django 3.1.3 on 2021-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_diaryitem_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='CV',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
