# Generated by Django 3.1.3 on 2021-04-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20210315_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leveldex',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
